#!/bin/bash
#PBS -N 144g_vsen
#PBS -e 144g_vsen_7s.err
#PBS -o 144g_vsen_7s.out
#PBS -l select=1:ncpus=12:mem=23Gb
#PBS -l cput=100:00:00
#PBS -l walltime=200:00:00
#PBS -l place=pack:shared
#PBS -q standard
#PBS -W group_list=mbsulli
#PBS -m bea
#PBS -M ssolonen@email.arizona.edu

# loading modules and adjusting environmental variables
. /usr/share/Modules/init/bash
module load bowtie2/2.1.0

/usr/bin/time -v bowtie2 --seed 7777 -p 12 -D 20 -R 3 -N 1 -L 20 -i S,1,0.50 -x /rsgrps1/mbsulli/sergei/ann_genomes/bowtie_db/144genomes.fa -1 /rsgrps1/mbsulli/sergei/ann_genomes/metagenomes/ISCX.2346.3.1885.TGACCA.1.fastq -2 /rsgrps1/mbsulli/sergei/ann_genomes/metagenomes/ISCX.2346.3.1885.TGACCA.2.fastq >/rsgrps1/mbsulli/sergei/ann_genomes/bowtie_runs/very_sensitive_run_144genomes_seed7777.sam
